# The frequency to save trained models when training.
save_step: 20
# The frequency to fetch and print output when training.
print_step: 10

# Path of trained parameter, to make prediction
init_from_params: "model/"
# The directory for saving model
save_model: "model/"
# Set seed for CE or debug
random_seed: None
# The pattern to match training data files.
training_file: "data_processer/data/train.ko.bpe,data_processer/data/train.zh.bpe"
# The pattern to match validation data files.
validation_file: "data_processer/data/dev.ko.bpe,data_processer/data/dev.zh.bpe"
# The pattern to match test data files.
predict_file: "data_processer/data/test.ko.bpe"
# The file to output the translation results of predict_file to.
output_file: "data_processer/data/predict.txt"
# The path of vocabulary file of source language.
src_vocab_fpath: "data_processer/data/src_vocab.txt"
# The path of vocabulary file of target language.
trg_vocab_fpath: "data_processer/data/trg_vocab.txt"
# The <bos>, <eos> and <unk> tokens in the dictionary.
special_token: ["<s>", "<e>", "<unk>"]

# Whether to use cuda
use_gpu: False

# Args for reader, see reader.py for details
batch_size: 8
infer_batch_size: 1
# Used to pad vocab size to be multiple of pad_factor.
pad_factor: 8

# Hyparams for training:
# The number of epoches for training
epoch: 1

# The hyper parameters for Adam optimizer.
# This static learning_rate will be applied to the LearningRateScheduler
# derived learning rate the to get the final learning rate.
learning_rate: 2.0
beta1: 0.9
beta2: 0.997
eps: 1e-9
# The parameters for learning rate scheduling.
warmup_steps: 8000
# The weight used to mix up the ground-truth distribution and the fixed
# uniform distribution in label smoothing when training.
# Set this as zero if label smoothing is not wanted.
label_smooth_eps: 0.1

# Hyparams for generation:
# The parameters for beam search.
beam_size: 5
max_out_len: 256
# The number of decoded sentences to output.
n_best: 1

# Hyparams for model:
# These following five vocabularies related configurations will be set
# automatically according to the passed vocabulary path and special tokens.
# Size of source word dictionary.
src_vocab_size: 41721
# Size of target word dictionay
trg_vocab_size: 46126
# Index for <bos> token
bos_idx: 0
# Index for <eos> token
eos_idx: 1
# Index for <unk> token
unk_idx: 2
# Max length of sequences deciding the size of position encoding table.
max_length: 256
# The dimension for word embeddings, which is also the last dimension of
# the input and output of multi-head attention, position-wise feed-forward
# networks, encoder and decoder.
d_model: 512
# Size of the hidden layer in position-wise feed-forward networks.
d_inner_hid: 2048
# Number of head used in multi-head attention.
n_head: 8
# Number of sub-layers to be stacked in the encoder and decoder.
n_layer: 6
# Dropout rates.
dropout: 0.1
# The flag indicating whether to share embedding and softmax weights.
# Vocabularies in source and target should be same for weight sharing.
weight_sharing: False
